# Generated by Django 2.1.5 on 2019-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='info_box',
            field=models.BooleanField(default=True),
        ),
    ]
